swagger:
  api tag标签,类分组
  ui布局
  api_method tag标签
  附带token参数
  自动解析
  入参
  出参
  参数名称
  参数示例值
  @requestbody
  @requestPara
  参数类型
  参数
  post body
  <swagger.version>2.9.2</swagger.version>
  <swagger.bootstrap-ui.version>1.9.6</swagger.bootstrap-ui.version>
  
  swagger3 使用感受 -- 不了解,升级, 混乱的知识体系
  
  树  图  children, 二叉树, n叉树