version : '3.8'
services:
  node1:
    image: redis
    container_name: redis_node1
    ports:
      - "13306:3306"
  node2:
    image: redis
    container_name: redis_node2
    ports:
      - "13307:3306"
